export const USER = {
    SIGN_UP: {
      SUCCESS: "USER_SIGN_UP_SUCCESS",
      FAILURE: "USER_SIGN_UP_FAILURE"
    },
    SET : {
       TOKEN: "USER_SET_TOKEN"
    },
    SIGN_IN: {
        SUCCESS: "USER_SIGN_IN_SUCCESS",
        FAILURE: "USER_SIGN_IN_FAILURE"
    },
    SIGN_OUT: {
        SUCCESS: "USER_SIGN_OUT_SUCCESS",
        FAILURE: "USER_SIGN_OUT_FAILURE"
    },
    RETRIEVE : {
        SUCCESS: "RETRIEVE_USER_SUCCESS",
        FAILURE: "RETRIEVE_USER_FAILURE"
    },
    GET_LIST: {
        SUCCESS: "USER_GET_LIST_SUCCESS",
        FAILURE: "USER_GET_LIST_FAILURE"
    }
};

export const INCIDENT = {
  GET : {
      SUCCESS: "GET_INCIDENTS_SUCCESS",
      FAILURE: "GET_INCIDENTS_FAIL"
  },

  CREATE : {
      SUCCESS: "POST_INCIDENT_SUCCESS",
      FAILURE: "POST_INCIDENT_FAILURE"
  }
};

export const STATUS = {
    ACTIVE: "ACTIVE",
    DELETE: "DELETE",
    PAUSE: "PAUSE"
};